### ISSUE TITLE
Error on Repo Files @ vrajroham/laravel-bitpay/src/Traits/LaravelBitpayTrait.php Line 21

### ISSUE THREAD

**Issue by olatolu** [vrajroham/laravel-bitpay#16]
Hello,

I detected an error on vrajroham/laravel-bitpay/src/Traits/LaravelBitpayTrait.php Line 21

new Tokens(
                $this->config['token'], //merchant
 ),

it should be

new Tokens(
                $this->config['token'] //merchant
),

Removed the "," after $this->config['token'] 

Weldone for the great work.

**Comment by vrajroham** [comment]
@olatolu Thank you so much for pointing this out. I have fixed the typo and released a new version here https://github.com/vrajroham/laravel-bitpay/releases/tag/v2.0.3

Happy Coding

**Comment by olatolu** [comment]
Well done.

Please do you have a clue of this?

Everything works fine on a local server but when I create a new pair and connects it to the BitPay account. The system is throwing error that private key could not be load or invalid when I try to pay.
