### ISSUE TITLE
Live sever issues

### ISSUE THREAD

**Issue by kizinho** [vrajroham/laravel-bitpay#20]
on local both test and live works but on live server am getting
BITPAY-INVOICE-CREATE: Failed to create invoice-> failed to serialize Invoice object : POST failed : Server error: `POST https://bitpay.com/invoices` resulted in a `500 Internal Server Error` response: {"error":"Account is suspended"}

but my account is active

**Comment by vrajroham** [comment]
This seems to be an upstream Bitpay server error. Try reaching support of Bitpay.
