### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Fossil01** [vrajroham/laravel-bitpay#25]
Any ETA on PHP 8 support?

**Comment by vrajroham** [comment]
As you know this is something that depends on the upstream library of bitpay. I can see you have already raised an issue there. https://github.com/bitpay/php-bitpay-client-v2/issues/57 

Once the upstream issue is fixed I can add support to PHP 8.0

**Comment by vrajroham** [comment]
@Fossil01 New release has been published supporting PHP 8.0 and upstream Bitpay SDK 5.0. Check out the new release here https://github.com/vrajroham/laravel-bitpay/releases/tag/v4.0.0
