### ISSUE TITLE
BITPAY-INVOICE-CREATE: Failed to create invoice: Unauthorized sin

### ISSUE THREAD

**Issue by umarpucitian** [vrajroham/laravel-bitpay#44]
I am getting this error while setting up my local test environment for bitPay. Please help me out with this
I wanna integrate this in Pakistan and bitpay is not available in our country so I am using proxy credentials to call the bitPay server

BITPAY-INVOICE-CREATE: Failed to create invoice-> failed to serialize Invoice object : failed to retrieve HTTP response body : Unauthorized sin

**Comment by alexstewartja** [comment]
@umarpucitian 

A little more details would be helpful:

- At what step of the setup process does your integration throw that error?
- Which OS/Distribution are you executing from?
- What PHP and Laravel version do you have installed?

P.S. Even a screenshot would come in handy.

**Comment by alexstewartja** [comment]
@umarpucitian 

Did you follow the exact instructions of the [Generate Key-Pair and API Token(s)](https://github.com/vrajroham/laravel-bitpay#generate-key-pair-and-api-tokens) step, ensuring you approve the generated token on your BitPay dashboard?

**Comment by alexstewartja** [comment]
Closing this, under the assumption that my last suggestion resolved your issue.
