### ISSUE TITLE
how to set proxy

### ISSUE THREAD

**Issue by umarpucitian** [vrajroham/laravel-bitpay#47]
Firstly I want to say thanks to you that you write this amazing package for our ease.
I am living in country where bitpay is restricted but I have to implement this while sitting here for some foreign client.
How to set proxy in it, please let me know the solution step by step as I have proxy credentials, how to set where to set and how can we set those in controller or env or wherever, please tell me the whole details.

Thanking you in advance

**Comment by alexstewartja** [comment]
Closing this, as it's outside the scope of this package.
