### ISSUE TITLE
Webhooks Notifications

### ISSUE THREAD

**Issue by umarpucitian** [vrajroham/laravel-bitpay#48]
I am not receiving webhook notifications from test account, my invoices are creating successfully but not getting notifications on invoices status changes(paid to confirmed and complete)  from bitPay. I am stuck with this, please help me resolve this

1- I have added this to the end of web.php
Route::bitPayWebhook();

2- Added this in eventserviceprovider
        BitpayWebhookReceived::class => [
            BitPayWebhookListener::class,
        ],
3-  Added this in webhook listener
    public function handle(BitpayWebhookReceived $event)
    {
        // Extract event payload
        $payload = $event->payload;
        Log::alert('test webhook');

        if (in_array($payload['event']['code'], array_keys(BitPayConstants::INVOICE_WEBHOOK_CODES))) {
            try {
                $invoice = LaravelBitpay::getInvoice($payload['data']['id']);

                $order = Order::find($invoice->getOrderId());

                if ($invoice->getToken() !== $order->payment_gateway_transaction_token) {
                    return;
                }
                $invoice_status = $invoice->getStatus();
            } catch (BitPayException $e) {
                Log::error($e);
            }
        }
    }

**Comment by alexstewartja** [comment]
Hi @umarpucitian 

Is your domain publicly accessible or are you developing locally?

**Comment by umarpucitian** [comment]
![capture2](https://user-images.githubusercontent.com/41008978/211731677-8264ccd5-e9d9-4601-a723-43777bf6b8ab.PNG)

Its not accessible, ht access password is added, its on our dev environment. Its get accessible after right credentials

**Comment by vrajroham** [comment]
@alexstewartja You pointed it out correctly.

In that case @umarpucitian your webhooks will not be delivered. I would suggest using the public endpoint to receive the webhook. For the testing purpose to verify webhooks are triggered from bitpay, you can use the https://webhook.site/ service.
